import { useEffect, useMemo, useState } from "react";

const api = import.meta.env.VITE_API_URL || "/api";
type Metric = { value: number | null; metric_source: string };
type Run = { id: string; target_id: string; target_version: string; status: string; started_at: string; dataset_hash: string; result_hash?: string; metrics?: Record<string, Metric> };
type Target = { id: string; name: string; adapter_type: string; version: string; languages: string[]; visibility: string };
type Benchmark = { id: string; name: string; version: string; case_count: number; languages: string[]; categories: string[]; published_at: string; dataset_hash: string; limitations: string[] };

async function request<T>(path: string, init?: RequestInit): Promise<T> {
  const response = await fetch(`${api}${path}`, init);
  if (!response.ok) throw new Error((await response.json().catch(() => ({}))).detail || "Service unavailable");
  return response.json();
}
const name = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, letter => letter.toUpperCase());
const metric = (m?: Metric) => m?.value == null ? "Not evaluated" : `${(m.value * 100).toFixed(1)}%`;

export default function App() {
  const [page, setPage] = useState(location.hash.slice(1) || "home");
  const [benchmark, setBenchmark] = useState<Benchmark>();
  const [targets, setTargets] = useState<Target[]>([]);
  const [runs, setRuns] = useState<Run[]>([]);
  const [selected, setSelected] = useState<Run>();
  const [results, setResults] = useState<any[]>([]);
  const [message, setMessage] = useState("Loading offline demo…");
  const go = (next: string) => { location.hash = next; setPage(next); };
  const reload = async () => { try { const [b, t, r] = await Promise.all([request<Benchmark[]>("/benchmarks"), request<Target[]>("/targets"), request<Run[]>("/runs")]); setBenchmark(b[0]); setTargets(t); setRuns(r); setMessage("Offline demo ready"); } catch (error) { setMessage(error instanceof Error ? error.message : "Offline backend unavailable"); } };
  useEffect(() => { reload(); }, []);
  useEffect(() => { const listener = () => setPage(location.hash.slice(1) || "home"); addEventListener("hashchange", listener); return () => removeEventListener("hashchange", listener); }, []);
  const runDemo = async (targetId: string) => { setMessage("Running deterministic demo…"); try { const run = await request<Run>(`/demo/run?target_id=${targetId}`, { method: "POST" }); await reload(); await openRun(run); go("runs"); setMessage("Immutable run created"); } catch (error) { setMessage(error instanceof Error ? error.message : "Run failed"); } };
  const openRun = async (run: Run) => { setSelected(await request<Run>(`/runs/${run.id}`)); setResults(await request<any[]>(`/runs/${run.id}/results`)); };
  const metrics = selected?.metrics || {};
  const compare = useMemo(() => runs.slice(0, 2), [runs]);
  return <div className="app"><header><a className="brand" href="#home" onClick={() => go("home")}>VAIS <span>Enterprise</span></a><nav>{[["home","Overview"],["benchmark","Benchmark"],["runs","Runs"],["compare","Compare"],["targets","Targets"],["methodology","Methodology"],["research","Research"]].map(([id,label]) => <a className={page === id ? "active" : ""} href={`#${id}`} key={id}>{label}</a>)}</nav><a className="lab" href="https://vaislabs.com/enterprise">VAIS Labs ↗</a></header><main>
    <div className="status"><span className="dot"></span>{message}</div>
    {page === "home" && <Home benchmark={benchmark} targets={targets} runDemo={runDemo} go={go}/>} 
    {page === "benchmark" && <BenchmarkPage benchmark={benchmark}/>} 
    {page === "runs" && <RunsPage runs={runs} selected={selected} results={results} openRun={openRun}/>} 
    {page === "compare" && <ComparePage runs={compare}/>} 
    {page === "targets" && <TargetsPage targets={targets} runDemo={runDemo}/>} 
    {page === "methodology" && <Methodology/>} {page === "research" && <Research/>}
  </main><footer>VAIS Enterprise v0.1 · Evaluation infrastructure, not AI safety certification.</footer></div>;
}

function Home({ benchmark, targets, runDemo, go }: {benchmark?: Benchmark; targets: Target[]; runDemo: (id:string)=>void; go:(id:string)=>void}) { return <><section className="hero"><p className="eyebrow">KZ/RU RAG & AGENT BENCHMARK</p><h1>Evaluate enterprise AI before it reaches production.</h1><p>Reproducible benchmarks for KZ/RU RAG, copilots and AI agents — with citation checks, hallucination tracking and versioned evidence.</p><div className="actions"><button onClick={() => go("benchmark")}>Explore benchmark</button><button className="secondary" onClick={() => runDemo("mock-a")}>Run demo benchmark</button></div></section><section className="grid three"><Card title="What is evaluated" text="Correctness, citations, unsupported claims, version awareness, cross-language behaviour and latency."/><Card title="A reproducible workflow" text="Versioned data → target response → deterministic evaluation → immutable run snapshot."/><Card title="Current status" text={`${benchmark?.case_count ?? "—"} self-written public demo cases. Protected tests and external adapters are planned.`}/></section><section className="workflow"><p className="eyebrow">DEMO FLOW</p><div>{["Select target", "Run benchmark", "Inspect evidence", "Compare runs"].map((item, i) => <span key={item}><b>0{i + 1}</b>{item}</span>)}</div></section><section className="callout"><div><p className="eyebrow">READY FOR A CONTROLLED DEMO</p><h2>Two deterministic targets. No invented results.</h2><p>Mock A follows the supplied evidence. Mock B has intentional citation and refusal failures so the comparison has real, inspectable differences.</p></div><div className="target-buttons">{targets.filter(t => t.adapter_type === "mock").map(t => <button key={t.id} className="secondary" onClick={() => runDemo(t.id)}>Run {t.name}</button>)}</div></section></> }
function BenchmarkPage({ benchmark }: {benchmark?: Benchmark}) { return <section><p className="eyebrow">PUBLIC DEMO DATASET</p><h1>{benchmark?.name || "Loading…"}</h1><div className="facts"><Fact label="Version" value={benchmark?.version}/><Fact label="Cases" value={String(benchmark?.case_count ?? "—")}/><Fact label="Languages" value={benchmark?.languages.join(" / ")}/><Fact label="Published" value={benchmark?.published_at}/></div><h2>Evaluation dimensions</h2><div className="grid three">{benchmark?.categories.map(category => <Card key={category} title={name(category)} text={category === "latency" ? "Deterministic timing captured per response." : "Transparent, deterministic demo evaluation."}/>)}</div><h2>Reproducibility</h2><pre>{benchmark?.dataset_hash}</pre><p className="muted">Limitations: {benchmark?.limitations.join(" ")}</p></section> }
function RunsPage({ runs, selected, results, openRun }: {runs: Run[]; selected?:Run; results:any[]; openRun:(r:Run)=>void}) { return <section><p className="eyebrow">IMMUTABLE SNAPSHOTS</p><h1>Benchmark runs</h1>{runs.length === 0 ? <Empty text="No runs yet. Run MockTarget A or B from Overview."/> : <div className="run-layout"><div className="list">{runs.map(run => <button className={selected?.id === run.id ? "run selected" : "run"} onClick={() => openRun(run)} key={run.id}><b>{run.target_id}</b><span>{new Date(run.started_at).toLocaleString()}</span><small>{run.status} · {run.id.slice(0,8)}</small></button>)}</div>{selected && <div className="details"><h2>{selected.target_id} <small>{selected.status}</small></h2><p className="mono">Run ID: {selected.id}</p><div className="metrics">{Object.entries(selected.metrics || {}).map(([key,value]) => <Fact key={key} label={name(key)} value={key.includes("latency") ? `${value.value ?? "Not evaluated"} ms` : metric(value)}/>)}</div><p className="mono">Dataset: {selected.dataset_hash}<br/>Result: {selected.result_hash}</p><h3>Per-case evidence</h3><table><thead><tr><th>Case</th><th>Expected</th><th>Actual</th><th>Citations</th></tr></thead><tbody>{results.map(item => <tr key={item.case_id}><td>{item.case_id}</td><td>{item.expected_answer}</td><td>{item.raw_answer}</td><td>{item.citations.map((c:any) => `${c.document_id} §${c.section}`).join(", ")}</td></tr>)}</tbody></table></div>}</div>}</section> }
function ComparePage({ runs }: {runs:Run[]}) { const keys = ["answer_correctness","citation_precision","citation_completeness","hallucination_rate","retrieval_recall_at_k","version_awareness","cross_language_score","latency_p50_ms","latency_p95_ms"]; return <section><p className="eyebrow">DIFFERENCES, NOT A WINNER</p><h1>Compare runs</h1>{runs.length < 2 ? <Empty text="Create two benchmark runs to compare them."/> : <table className="compare"><thead><tr><th>Metric</th>{runs.map(r=><th key={r.id}>{r.target_id}<small>{r.id.slice(0,8)}</small></th>)}</tr></thead><tbody>{keys.map(key=><tr key={key}><td>{name(key)}</td>{runs.map(r => <td key={r.id}>{key.includes("latency") ? `${r.metrics?.[key]?.value ?? "Not evaluated"} ms` : metric(r.metrics?.[key])}</td>)}</tr>)}</tbody></table>}<p className="muted">Values are deterministic demo outputs. Retrieval is explicitly not evaluated because the mock receives the full evidence set.</p></section> }
function TargetsPage({ targets, runDemo }: {targets:Target[];runDemo:(id:string)=>void}) { return <section><p className="eyebrow">TARGET REGISTRY</p><h1>Evaluation targets</h1><div className="grid three">{targets.map(target => <article className="card" key={target.id}><span className="pill">{target.adapter_type}</span><h2>{target.name}</h2><p>Version {target.version}<br/>Languages: {target.languages.join(", ")}<br/>Visibility: {target.visibility}</p>{target.adapter_type === "mock" ? <button onClick={() => runDemo(target.id)}>Run demo</button> : <p className="muted">Execution planned. Credentials are not persisted.</p>}</article>)}</div><section className="callout compact"><div><h2>Bring an adapter</h2><p>OpenAI-compatible and Generic HTTP JSON metadata can be registered through the API. Private/localhost endpoints are blocked; secrets are never stored.</p></div><span className="pill">Preview</span></section></section> }
function Methodology(){return <section className="prose"><p className="eyebrow">METHOD</p><h1>Transparent by default.</h1><h2>What the score means</h2><p>Answer matching, citation coverage, unsupported claims and latency are deterministic metrics in v0.1. Human review is not available. LLM-as-judge is not evaluated and is never blended silently with deterministic scores.</p><h2>Versioned evidence</h2><p>Every run records its benchmark version, target version, configuration hash, dataset hash, evaluator version and result hash. A completed run is a snapshot, never an editable report.</p><h2>Limitations</h2><p>The public set contains self-written synthetic policy documents. It is suitable for exploring the protocol, not for certifying an AI system.</p><blockquote>VAIS Enterprise does not certify that an AI system is safe or production-ready. Benchmark results describe performance under the published evaluation protocol.</blockquote></section>}
function Research(){return <section className="prose"><p className="eyebrow">RESEARCH INFRASTRUCTURE</p><h1>Evaluation for the context systems actually face.</h1><h2>KZ/RU low-resource challenges</h2><p>Cross-language questions can obscure weak retrieval, unsupported translation or a citation that does not actually support the answer. Evaluation should retain the language and evidence path rather than hide them behind one aggregate score.</p><h2>Roadmap</h2><div className="grid three"><Card title="Private benchmarks" text="Planned: protected evaluation sets and private corpora."/><Card title="Agent workflows" text="Planned: tool-use and workflow evaluation."/><Card title="Continuous regression" text="Planned: version-to-version checks before release."/></div></section>}
function Card({title,text}:{title:string;text:string}){return <article className="card"><h2>{title}</h2><p>{text}</p></article>}; function Fact({label,value}:{label:string;value?:string}){return <div className="fact"><span>{label}</span><b>{value || "—"}</b></div>}; function Empty({text}:{text:string}){return <div className="empty">{text}</div>}
